# Generated by Django 2.0.3 on 2018-03-18 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True)),
                ('read', models.BooleanField()),
                ('usertype', models.CharField(choices=[('FC', 'Consultant'), ('UC', 'User')], max_length=2)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Consultant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=255)),
                ('lname', models.CharField(max_length=255)),
                ('email1', models.EmailField(max_length=500, unique=True)),
                ('contactno1', models.CharField(blank=True, max_length=255)),
                ('email2', models.EmailField(blank=True, max_length=500)),
                ('contactno2', models.CharField(blank=True, max_length=255)),
                ('password', models.CharField(max_length=50)),
                ('preferedcontact1', models.CharField(choices=[('E1', 'Primary Email'), ('E2', 'Secondary Email'), ('P1', 'Primary Contact No'), ('P2', 'Secondary Contact No')], max_length=2)),
                ('preferedcontact2', models.CharField(choices=[('E1', 'Primary Email'), ('E2', 'Secondary Email'), ('P1', 'Primary Contact No'), ('P2', 'Secondary Contact No')], max_length=2)),
                ('verified', models.BooleanField()),
                ('lastLogin', models.DateTimeField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ConsultantCoverage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('JH', 'Johor'), ('KH', 'Kedah'), ('KN', 'Kelantan'), ('KL', 'Kuala Lumpur'), ('LA', 'Labuan'), ('ME', 'Melaka'), ('NS', 'Negeri Sembilan'), ('PH', 'Pahang'), ('PK', 'Perak'), ('PL', 'Perlis'), ('PG', 'Pulau Pinang'), ('PJ', 'Putrajaya'), ('SA', 'Sabah'), ('SK', 'Sarawak'), ('SL', 'Selangor'), ('TE', 'Terengganu')], default='KL', max_length=2)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('consultant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Consultant')),
            ],
        ),
        migrations.CreateModel(
            name='ConsultantServices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(choices=[('FP', 'Financial Planner'), ('LI', 'Life Insurance'), ('IN', 'Investments'), ('TF', 'Trust Fund'), ('WW', 'Will Writing')], default='FP', max_length=2)),
                ('company', models.CharField(blank=True, max_length=255)),
                ('registrationno', models.CharField(blank=True, max_length=255)),
                ('active', models.BooleanField()),
                ('activesince', models.DateTimeField()),
                ('yearsofexpirience', models.IntegerField()),
                ('clientscale', models.CharField(choices=[('SM', 'Small (< 10)'), ('SE', 'Small to Medium (> 50)'), ('ME', 'Medium (> 100)'), ('MH', 'Medium to High (> 150)'), ('HI', 'High (> 200)')], default='SM', max_length=2)),
                ('proof', models.ImageField(max_length=50000, upload_to=None)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('consultant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Consultant')),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(choices=[('FP', 'Financial Planner'), ('LI', 'Life Insurance'), ('IN', 'Investments'), ('TF', 'Trust Fund'), ('WW', 'Will Writing')], max_length=2)),
                ('reviewsubmited', models.BooleanField()),
                ('active', models.BooleanField()),
                ('completed', models.BooleanField()),
                ('message', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('consultant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Consultant')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.IntegerField()),
                ('message', models.TextField(blank=True)),
                ('public', models.BooleanField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=255, unique=True)),
                ('lname', models.CharField(max_length=255, unique=True)),
                ('email', models.EmailField(max_length=500, unique=True)),
                ('contactno', models.CharField(blank=True, max_length=255)),
                ('authtype', models.CharField(choices=[('FB', 'Facebook'), ('EM', 'Email'), ('GO', 'Google')], default='EM', max_length=2)),
                ('password', models.CharField(blank=True, max_length=50)),
                ('showemail', models.NullBooleanField()),
                ('showcontactno', models.NullBooleanField()),
                ('verified', models.BooleanField()),
                ('lastLogin', models.DateTimeField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='review',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Users'),
        ),
        migrations.AddField(
            model_name='request',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Users'),
        ),
        migrations.AddField(
            model_name='chat',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Users'),
        ),
    ]
