# Generated by Django 2.0.3 on 2018-04-25 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20180425_0100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultantcoverage',
            name='consultant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coverages', to='api.Consultant'),
        ),
        migrations.AlterField(
            model_name='consultantservices',
            name='consultant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='api.Consultant'),
        ),
    ]
