// <auto-generated />
using System;
using Fmarketer.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Fmarketer.Models.Migrations
{
    [DbContext(typeof(MainContext))]
    [Migration("20180622075616_FixedMappingv2")]
    partial class FixedMappingv2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Fmarketer.Models.Model.Admin", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Contact");

                    b.Property<DateTime>("Created");

                    b.Property<string>("Email");

                    b.Property<string>("FirstName");

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("LastName");

                    b.Property<DateTime>("Updated");

                    b.Property<Guid?>("_CredentialId");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasFilter("[Email] IS NOT NULL");

                    b.HasIndex("_CredentialId");

                    b.ToTable("Admins");
                });

            modelBuilder.Entity("Fmarketer.Models.Model.Chat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Attachment");

                    b.Property<DateTime>("Created");

                    b.Property<int>("From");

                    b.Property<bool>("IsDeleted");

                    b.Property<bool>("IsRead");

                    b.Property<string>("Message");

                    b.Property<DateTime>("Updated");

                    b.Property<Guid?>("_RequestId");

                    b.HasKey("Id");

                    b.HasIndex("_RequestId");

                    b.ToTable("Chats");
                });

            modelBuilder.Entity("Fmarketer.Models.Model.Consultant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Contact");

                    b.Property<string>("Contact2");

                    b.Property<int>("ContactOpt");

                    b.Property<int>("ContactOpt2");

                    b.Property<DateTime>("Created");

                    b.Property<string>("Email");

                    b.Property<string>("Email2");

                    b.Property<string>("FirstName");

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("LastName");

                    b.Property<bool>("ShowContact");

                    b.Property<bool>("ShowEmail");

                    b.Property<DateTime>("Updated");

                    b.Property<Guid?>("_CredentialId");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasFilter("[Email] IS NOT NULL");

                    b.HasIndex("_CredentialId");

                    b.ToTable("Consultants");
                });

            modelBuilder.Entity("Fmarketer.Models.Model.ConsultantCoverage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Created");

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("Location");

                    b.Property<int>("State");

                    b.Property<DateTime>("Updated");

                    b.Property<Guid?>("_ConsultantId");

                    b.HasKey("Id");

                    b.HasIndex("_ConsultantId");

                    b.ToTable("Consultantcoverages");
                });

            modelBuilder.Entity("Fmarketer.Models.Model.ConsultantService", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("ActiveSince");

                    b.Property<int>("ClientScale");

                    b.Property<string>("Company");

                    b.Property<DateTime>("Created");

                    b.Property<bool>("IsDeleted");

                    b.Property<bool>("LicenseActive");

                    b.Property<string>("Proof");

                    b.Property<string>("RegistrationNo");

                    b.Property<int>("Service");

                    b.Property<DateTime>("Updated");

                    b.Property<int>("YearsOfExp");

                    b.Property<Guid?>("_ConsultantId");

                    b.HasKey("Id");

                    b.HasIndex("_ConsultantId");

                    b.ToTable("ConsultantServices");
                });

            modelBuilder.Entity("Fmarketer.Models.Model.Credential", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AuthType");

                    b.Property<DateTime>("Created");

                    b.Property<int>("CredentialState");

                    b.Property<string>("Email");

                    b.Property<bool>("IsDeleted");

                    b.Property<DateTime>("LastLogin");

                    b.Property<int>("NumberOfTry");

                    b.Property<string>("Password");

                    b.Property<string>("Salt");

                    b.Property<DateTime>("Updated");

                    b.Property<int>("UserType");

                    b.Property<bool>("Verified");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasFilter("[Email] IS NOT NULL");

                    b.ToTable("Credentials");
                });

            modelBuilder.Entity("Fmarketer.Models.Model.Request", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Created");

                    b.Property<bool>("IsActive");

                    b.Property<bool>("IsCompleted");

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("Message");

                    b.Property<int>("Service");

                    b.Property<DateTime>("Updated");

                    b.Property<Guid?>("_ConsultantId");

                    b.Property<Guid?>("_ReviewId");

                    b.Property<Guid?>("_UserId");

                    b.HasKey("Id");

                    b.HasIndex("_ConsultantId");

                    b.HasIndex("_ReviewId");

                    b.HasIndex("_UserId");

                    b.ToTable("Requests");
                });

            modelBuilder.Entity("Fmarketer.Models.Model.Review", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Created");

                    b.Property<bool>("IsDeleted");

                    b.Property<bool>("IsPublic");

                    b.Property<string>("Message");

                    b.Property<int>("Star");

                    b.Property<DateTime>("Updated");

                    b.HasKey("Id");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("Fmarketer.Models.Model.SecurityToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("AuthenticatedTime");

                    b.Property<DateTime>("Created");

                    b.Property<DateTime>("ExpiryTime");

                    b.Property<bool>("IsDeleted");

                    b.Property<DateTime>("Updated");

                    b.Property<Guid?>("_CredentialId");

                    b.HasKey("Id");

                    b.HasIndex("_CredentialId");

                    b.ToTable("SecurityTokens");
                });

            modelBuilder.Entity("Fmarketer.Models.Model.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Contact");

                    b.Property<DateTime>("Created");

                    b.Property<string>("Email");

                    b.Property<string>("FirstName");

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("LastName");

                    b.Property<bool>("ShowContact");

                    b.Property<bool>("ShowEmail");

                    b.Property<DateTime>("Updated");

                    b.Property<Guid?>("_CredentialId");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasFilter("[Email] IS NOT NULL");

                    b.HasIndex("_CredentialId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Fmarketer.Models.Model.Admin", b =>
                {
                    b.HasOne("Fmarketer.Models.Model.Credential", "_Credential")
                        .WithMany()
                        .HasForeignKey("_CredentialId");
                });

            modelBuilder.Entity("Fmarketer.Models.Model.Chat", b =>
                {
                    b.HasOne("Fmarketer.Models.Model.Request", "_Request")
                        .WithMany("_Chats")
                        .HasForeignKey("_RequestId");
                });

            modelBuilder.Entity("Fmarketer.Models.Model.Consultant", b =>
                {
                    b.HasOne("Fmarketer.Models.Model.Credential", "_Credential")
                        .WithMany()
                        .HasForeignKey("_CredentialId");
                });

            modelBuilder.Entity("Fmarketer.Models.Model.ConsultantCoverage", b =>
                {
                    b.HasOne("Fmarketer.Models.Model.Consultant", "_Consultant")
                        .WithMany("_Coverages")
                        .HasForeignKey("_ConsultantId");
                });

            modelBuilder.Entity("Fmarketer.Models.Model.ConsultantService", b =>
                {
                    b.HasOne("Fmarketer.Models.Model.Consultant", "_Consultant")
                        .WithMany("_Services")
                        .HasForeignKey("_ConsultantId");
                });

            modelBuilder.Entity("Fmarketer.Models.Model.Request", b =>
                {
                    b.HasOne("Fmarketer.Models.Model.Consultant", "_Consultant")
                        .WithMany("_Requests")
                        .HasForeignKey("_ConsultantId");

                    b.HasOne("Fmarketer.Models.Model.Review", "_Review")
                        .WithMany()
                        .HasForeignKey("_ReviewId");

                    b.HasOne("Fmarketer.Models.Model.User", "_User")
                        .WithMany("_Requests")
                        .HasForeignKey("_UserId");
                });

            modelBuilder.Entity("Fmarketer.Models.Model.SecurityToken", b =>
                {
                    b.HasOne("Fmarketer.Models.Model.Credential", "_Credential")
                        .WithMany()
                        .HasForeignKey("_CredentialId");
                });

            modelBuilder.Entity("Fmarketer.Models.Model.User", b =>
                {
                    b.HasOne("Fmarketer.Models.Model.Credential", "_Credential")
                        .WithMany()
                        .HasForeignKey("_CredentialId");
                });
#pragma warning restore 612, 618
        }
    }
}
